server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active:
      - native
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS